//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.05.06 at 12:44:58 MDT 
//


package org.megatome.example.jaxbgen;


/**
 * Java content class for ACK element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/ChadDev/ws_example/example/WEB-INF/xml/user.xsd line 36)
 * <p>
 * <pre>
 * &lt;element name="ACK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * </pre>
 * 
 */
public interface ACK
    extends javax.xml.bind.Element
{


    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getValue();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setValue(java.lang.String value);

}
