//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.04 at 02:32:08 MST 
//


package org.megatome.frame2.jaxbgen.impl;

public class ItemsImpl
    extends org.megatome.frame2.jaxb.JaxbEventBase
    implements org.megatome.frame2.jaxbgen.Items, java.io.Serializable, com.sun.xml.bind.JAXBObject, org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallableObject, org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializable, org.megatome.frame2.jaxbgen.impl.runtime.ValidatableObject
{

    private final static long serialVersionUID = 1L;
    protected com.sun.xml.bind.util.ListImpl _Item = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
    public final static java.lang.Class version = (org.megatome.frame2.jaxbgen.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.megatome.frame2.jaxbgen.Items.class);
    }

    public java.util.List getItem() {
        return _Item;
    }

    public org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context) {
        return new org.megatome.frame2.jaxbgen.impl.ItemsImpl.Unmarshaller(context);
    }

    public void serializeBody(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = _Item.size();
        while (idx1 != len1) {
            context.startElement("", "item");
            int idx_0 = idx1;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Item.get(idx_0 ++)), "Item");
            context.endNamespaceDecls();
            int idx_1 = idx1;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Item.get(idx_1 ++)), "Item");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Item.get(idx1 ++)), "Item");
            context.endElement();
        }
    }

    public void serializeAttributes(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = _Item.size();
        while (idx1 != len1) {
            idx1 += 1;
        }
    }

    public void serializeURIs(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = _Item.size();
        while (idx1 != len1) {
            idx1 += 1;
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.megatome.frame2.jaxbgen.Items.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gramm"
+"ar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expression"
+"\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/l"
+"ang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\u0002\u000b-\u00d5ppsr\u0000 com.sun.msv.gramm"
+"ar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0002\u000b-\u00casr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002"
+"\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001eco"
+"m.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAt"
+"tributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0002\u000b-\u00c7q\u0000~\u0000\np\u0000sr\u0000\u001fcom.sun.msv"
+".grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0002\u000b-\u00bcppsq\u0000~\u0000\u000b\u0001G\u00c1\u00fdpp\u0000sq\u0000~"
+"\u0000\u0000\u0001G\u00c1\u00f2ppsq\u0000~\u0000\u0006\u0001G\u00c1\u00e7q\u0000~\u0000\npsr\u0000 com.sun.msv.grammar.AttributeExp"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\fxq\u0000~\u0000\u0003\u0001G\u00c1\u00e4q\u0000~\u0000\npsr\u00002c"
+"om.sun.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xq\u0000~\u0000\u0003\u0000\u0000\u0000\bsq\u0000~\u0000\t\u0001q\u0000~\u0000\u0017sr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000c"
+"om.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq"
+"\u0000~\u0000\u0003\u0000\u0000\u0000\tq\u0000~\u0000\u0018psr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000\u001fxq\u0000"
+"~\u0000\u001at\u0000*org.megatome.frame2.jaxbgen.Items.ItemTypet\u0000+http://ja"
+"va.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u0000\u0000\u00c3k\u00bappsq\u0000~\u0000\u0014\u0000\u00c3k\u00afq\u0000~\u0000"
+"\npsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/rel"
+"axng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/"
+"util/StringPair;xq\u0000~\u0000\u0003\u0000\u0097\u00ed\u00fdppsr\u0000\"com.sun.msv.datatype.xsd.Qna"
+"meType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicT"
+"ype\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003"
+"L\u0000\fnamespaceUriq\u0000~\u0000\u001fL\u0000\btypeNameq\u0000~\u0000\u001fL\u0000\nwhiteSpacet\u0000.Lcom/sun"
+"/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org"
+"/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpa"
+"ceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd."
+"WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expr"
+"ession$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.m"
+"sv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001fL\u0000\fnamespaceUR"
+"Iq\u0000~\u0000\u001fxpq\u0000~\u00000q\u0000~\u0000/sq\u0000~\u0000\u001et\u0000\u0004typet\u0000)http://www.w3.org/2001/XML"
+"Schema-instanceq\u0000~\u0000\u001dsq\u0000~\u0000\u001et\u0000\u0004itemt\u0000\u0000q\u0000~\u0000\u001dsr\u0000\"com.sun.msv.gra"
+"mmar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/gra"
+"mmar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Exp"
+"ressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006pare"
+"ntq\u0000~\u0000?[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/Expression;xp\u0000\u0000\u0000\u0006\u0000\u0000\u0000"
+"9pur\u0000![Lcom.sun.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppp"
+"pppppppppppppppppppppppppppppppppppppppppppppppq\u0000~\u0000\u0013pq\u0000~\u0000\u0010pp"
+"ppppppq\u0000~\u0000\u0012ppppq\u0000~\u0000\bppppppppppq\u0000~\u0000\u0005ppppppppppppppppppppppppp"
+"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
+"ppq\u0000~\u0000#pppppppppppppppppppppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public static class ItemTypeImpl
        extends org.megatome.frame2.jaxb.JaxbEventBase
        implements org.megatome.frame2.jaxbgen.Items.ItemType, java.io.Serializable, com.sun.xml.bind.JAXBObject, org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallableObject, org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializable, org.megatome.frame2.jaxbgen.impl.runtime.ValidatableObject
    {

        private final static long serialVersionUID = 1L;
        protected java.lang.String _Comment;
        protected java.math.BigDecimal _USPrice;
        protected java.lang.String _ProductName;
        protected java.lang.String _PartNum;
        protected java.util.Calendar _ShipDate;
        protected java.math.BigInteger _Quantity;
        public final static java.lang.Class version = (org.megatome.frame2.jaxbgen.impl.JAXBVersion.class);
        private static com.sun.msv.grammar.Grammar schemaFragment;

        private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
            return (org.megatome.frame2.jaxbgen.Items.ItemType.class);
        }

        public java.lang.String getComment() {
            return _Comment;
        }

        public void setComment(java.lang.String value) {
            _Comment = value;
        }

        public java.math.BigDecimal getUSPrice() {
            return _USPrice;
        }

        public void setUSPrice(java.math.BigDecimal value) {
            _USPrice = value;
        }

        public java.lang.String getProductName() {
            return _ProductName;
        }

        public void setProductName(java.lang.String value) {
            _ProductName = value;
        }

        public java.lang.String getPartNum() {
            return _PartNum;
        }

        public void setPartNum(java.lang.String value) {
            _PartNum = value;
        }

        public java.util.Calendar getShipDate() {
            return _ShipDate;
        }

        public void setShipDate(java.util.Calendar value) {
            _ShipDate = value;
        }

        public java.math.BigInteger getQuantity() {
            return _Quantity;
        }

        public void setQuantity(java.math.BigInteger value) {
            _Quantity = value;
        }

        public org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context) {
            return new org.megatome.frame2.jaxbgen.impl.ItemsImpl.ItemTypeImpl.Unmarshaller(context);
        }

        public void serializeBody(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
            context.startElement("", "productName");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _ProductName), "ProductName");
            } catch (java.lang.Exception e) {
                org.megatome.frame2.jaxbgen.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
            context.startElement("", "quantity");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInteger(((java.math.BigInteger) _Quantity)), "Quantity");
            } catch (java.lang.Exception e) {
                org.megatome.frame2.jaxbgen.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
            context.startElement("", "USPrice");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDecimal(((java.math.BigDecimal) _USPrice)), "USPrice");
            } catch (java.lang.Exception e) {
                org.megatome.frame2.jaxbgen.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
            if (_Comment!= null) {
                context.startElement("", "comment");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _Comment), "Comment");
                } catch (java.lang.Exception e) {
                    org.megatome.frame2.jaxbgen.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_ShipDate!= null) {
                context.startElement("", "shipDate");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(javax.xml.bind.DatatypeConverter.printDate(((java.util.Calendar) _ShipDate)), "ShipDate");
                } catch (java.lang.Exception e) {
                    org.megatome.frame2.jaxbgen.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
        }

        public void serializeAttributes(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
            context.startAttribute("", "partNum");
            try {
                context.text(((java.lang.String) _PartNum), "PartNum");
            } catch (java.lang.Exception e) {
                org.megatome.frame2.jaxbgen.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }

        public void serializeURIs(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
        }

        public java.lang.Class getPrimaryInterface() {
            return (org.megatome.frame2.jaxbgen.Items.ItemType.class);
        }

        public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
            if (schemaFragment == null) {
                schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava"
+"/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\u000f\u0012\u00ea\u00f4ppsq\u0000~\u0000\u0000\rIN\u00bdppsq\u0000~\u0000\u0000\t"
+"\u0097\u00cd)ppsq\u0000~\u0000\u0000\u0006\u00ff\u0001tppsq\u0000~\u0000\u0000\u0003\u00de\u00c6\nppsr\u0000\'com.sun.msv.grammar.trex.El"
+"ementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/N"
+"ameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aign"
+"oreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0001*\u00cdApp\u0000sq\u0000~"
+"\u0000\u0000\u0001*\u00cd6ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLo"
+"rg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/su"
+"n/msv/util/StringPair;xq\u0000~\u0000\u0003\u00002W\u00c8ppsr\u0000#com.sun.msv.datatype.x"
+"sd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.data"
+"type.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatyp"
+"e.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XS"
+"DatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L"
+"\u0000\btypeNameq\u0000~\u0000\u0017L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/Whi"
+"teSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006str"
+"ingsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpre"
+"ssion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0"
+"t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0017L\u0000\fnamespaceURIq\u0000~\u0000\u0017xpq\u0000~\u0000\u001bq\u0000~\u0000\u001as"
+"r\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0000\u00f8uippsr\u0000 c"
+"om.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tname"
+"Classq\u0000~\u0000\u000bxq\u0000~\u0000\u0003\u0000\u00f8u^sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005value"
+"xp\u0000psq\u0000~\u0000\u000f\u0000\u0097\u00ed\u00fdppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0014q\u0000~\u0000\u001at\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSp"
+"aceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001dq\u0000~\u0000 sq\u0000~\u0000!q\u0000~\u0000,q\u0000~\u0000\u001as"
+"r\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNam"
+"eq\u0000~\u0000\u0017L\u0000\fnamespaceURIq\u0000~\u0000\u0017xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-insta"
+"ncesr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tsq\u0000~\u0000\'\u0001psq\u0000~\u00000t\u0000\u000bproductNamet\u0000\u0000sq\u0000~\u0000\n\u0002\u00b3\u00f8\u00c4pp\u0000"
+"sq\u0000~\u0000\u0000\u0002\u00b3\u00f8\u00b9ppsq\u0000~\u0000\u000f\u0000\u0097\u00d06ppsr\u0000*com.sun.msv.datatype.xsd.MaxExcl"
+"usiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.RangeFacet"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv"
+".datatype.xsd.DataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000"
+"*com.sun.msv.datatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisF"
+"acetFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypet\u0000)Lcom/sun/msv/dat"
+"atype/xsd/XSDatatypeImpl;L\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/data"
+"type/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000\u0017xq\u0000~\u0000\u0016q\u0000~\u0000:pq\u0000~\u0000.\u0000\u0000sr"
+"\u0000,com.sun.msv.datatype.xsd.PositiveIntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000"
+"$com.sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun."
+"msv.datatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetsq"
+"\u0000~\u0000Cxq\u0000~\u0000\u0014q\u0000~\u0000\u001at\u0000\u000fpositiveIntegerq\u0000~\u0000.sr\u0000*com.sun.msv.dataty"
+"pe.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000?ppq\u0000~\u0000.\u0000\u0000sr\u0000/com.su"
+"n.msv.datatype.xsd.NonNegativeIntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Gq\u0000"
+"~\u0000\u001at\u0000\u0012nonNegativeIntegerq\u0000~\u0000.sq\u0000~\u0000Kppq\u0000~\u0000.\u0000\u0000sq\u0000~\u0000Gq\u0000~\u0000\u001at\u0000\u0007in"
+"tegerq\u0000~\u0000.sr\u0000,com.sun.msv.datatype.xsd.FractionDigitsFacet\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.DataTypeWithLe"
+"xicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000Bppq\u0000~\u0000.\u0001\u0000sr\u0000#com.sun.ms"
+"v.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0014q\u0000~\u0000\u001at\u0000\u0007decimalq\u0000~"
+"\u0000.q\u0000~\u0000Wt\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000Qt\u0000\fminInclusivesr\u0000)com.sun."
+"msv.datatype.xsd.IntegerValueType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0005valueq\u0000~\u0000\u0017xr\u0000"
+"\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xpt\u0000\u00010q\u0000~\u0000Nq\u0000~\u0000Zsq\u0000~\u0000[t\u0000\u00011q\u0000~\u0000It"
+"\u0000\fmaxExclusivesq\u0000~\u0000[t\u0000\u0003100q\u0000~\u0000 sq\u0000~\u0000!t\u0000\u0017positiveInteger-deri"
+"vedq\u0000~\u0000:sq\u0000~\u0000#\u0002\u001c(~ppsq\u0000~\u0000%\u0002\u001c(sq\u0000~\u0000(pq\u0000~\u0000)sq\u0000~\u00000q\u0000~\u00003q\u0000~\u00004q\u0000~"
+"\u00006sq\u0000~\u00000t\u0000\bquantityq\u0000~\u0000:sq\u0000~\u0000\n\u0003 ;epp\u0000sq\u0000~\u0000\u0000\u0003 ;Zppsq\u0000~\u0000\u000f\u0001z\u0017wp"
+"pq\u0000~\u0000Wq\u0000~\u0000 sq\u0000~\u0000!q\u0000~\u0000Xq\u0000~\u0000\u001asq\u0000~\u0000#\u0001\u00a6#\u00deppsq\u0000~\u0000%\u0001\u00a6#\u00d3q\u0000~\u0000(pq\u0000~\u0000)"
+"sq\u0000~\u00000q\u0000~\u00003q\u0000~\u00004q\u0000~\u00006sq\u0000~\u00000t\u0000\u0007USPriceq\u0000~\u0000:sq\u0000~\u0000#\u0002\u0098\u00cb\u00b0ppsq\u0000~\u0000\n"
+"\u0002\u0098\u00cb\u00a5q\u0000~\u0000(p\u0000sq\u0000~\u0000\u0000\u0002\u0098\u00cb\u009appq\u0000~\u0000\u0012sq\u0000~\u0000#\u0002fs\u00cdppsq\u0000~\u0000%\u0002fs\u00c2q\u0000~\u0000(pq\u0000~\u0000"
+")sq\u0000~\u00000q\u0000~\u00003q\u0000~\u00004q\u0000~\u00006sq\u0000~\u00000t\u0000\u0007commentq\u0000~\u0000:q\u0000~\u00006sq\u0000~\u0000#\u0003\u00b1\u0081\u008fpp"
+"sq\u0000~\u0000\n\u0003\u00b1\u0081\u0084q\u0000~\u0000(p\u0000sq\u0000~\u0000\u0000\u0003\u00b1\u0081yppsq\u0000~\u0000\u000f\u0001\u00c2\b\u00c0ppsr\u0000!com.sun.msv.dat"
+"atype.xsd.DateType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000)com.sun.msv.datatype.xsd.Da"
+"teTimeBaseType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u0000\u0014q\u0000~\u0000\u001at\u0000\u0004dateq\u0000~\u0000.q\u0000~\u0000 sq\u0000~\u0000!q"
+"\u0000~\u0000\u0083q\u0000~\u0000\u001asq\u0000~\u0000#\u0001\u00efx\u00b4ppsq\u0000~\u0000%\u0001\u00efx\u00a9q\u0000~\u0000(pq\u0000~\u0000)sq\u0000~\u00000q\u0000~\u00003q\u0000~\u00004q\u0000"
+"~\u00006sq\u0000~\u00000t\u0000\bshipDateq\u0000~\u0000:q\u0000~\u00006sq\u0000~\u0000%\u0001\u00c9\u009c2ppsq\u0000~\u0000\u000f\u00015v\u00b2ppsr\u0000%co"
+"m.sun.msv.datatype.xsd.PatternFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001[\u0000\bpatternst\u0000\u0013"
+"[Ljava/lang/String;xq\u0000~\u0000Tq\u0000~\u0000:t\u0000\u0003SKUq\u0000~\u0000\u001e\u0000\u0000q\u0000~\u0000\u0019q\u0000~\u0000\u0019t\u0000\u0007patt"
+"ernur\u0000\u0013[Ljava.lang.String;\u00ad\u00d2V\u00e7\u00e9\u001d{G\u0002\u0000\u0000xp\u0000\u0000\u0000\u0001t\u0000\u000e\\d{3}-[A-Z]{2}"
+"q\u0000~\u0000 sq\u0000~\u0000!q\u0000~\u0000\u008fq\u0000~\u0000:sq\u0000~\u00000t\u0000\u0007partNumq\u0000~\u0000:sr\u0000\"com.sun.msv.gr"
+"ammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/gr"
+"ammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Ex"
+"pressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006par"
+"entq\u0000~\u0000\u0098[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/Expression;xp\u0000\u0000\u0000\u0011\u0000\u0000"
+"\u00009pur\u0000![Lcom.sun.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfppp"
+"ppppppppppppq\u0000~\u0000\u0006ppppppppppppq\u0000~\u0000wpppppppppppppppq\u0000~\u0000$pppppp"
+"ppppppq\u0000~\u0000fpppppq\u0000~\u0000~ppppppppppq\u0000~\u0000\u0085ppppppppppq\u0000~\u0000|pppppppq\u0000"
+"~\u0000\u0005ppppppppppppppppq\u0000~\u0000<pppppq\u0000~\u0000\u0007pq\u0000~\u0000\bpppppq\u0000~\u0000\tpppppppppp"
+"pppppppppppppppppppppppppppq\u0000~\u0000vppppppq\u0000~\u0000lq\u0000~\u0000opppppppq\u0000~\u0000\u000e"
+"pppppq\u0000~\u0000tpppppp"));
            }
            return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
        }

        public class Unmarshaller
            extends org.megatome.frame2.jaxbgen.impl.runtime.AbstractUnmarshallingEventHandlerImpl
        {


            public Unmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context) {
                super(context, "-------------------");
            }

            protected Unmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context, int startState) {
                this(context);
                state = startState;
            }

            public java.lang.Object owner() {
                return org.megatome.frame2.jaxbgen.impl.ItemsImpl.ItemTypeImpl.this;
            }

            public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  6 :
                            if (("quantity" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 7;
                                return ;
                            }
                            break;
                        case  15 :
                            if (("shipDate" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 16;
                                return ;
                            }
                            state = 18;
                            continue outer;
                        case  3 :
                            if (("productName" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 4;
                                return ;
                            }
                            break;
                        case  9 :
                            if (("USPrice" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 10;
                                return ;
                            }
                            break;
                        case  0 :
                            attIdx = context.getAttribute("", "partNum");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 3;
                                continue outer;
                            }
                            break;
                        case  18 :
                            revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        case  12 :
                            if (("comment" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 13;
                                return ;
                            }
                            state = 15;
                            continue outer;
                    }
                    super.enterElement(___uri, ___local, ___qname, __atts);
                    break;
                }
            }

            private void eatText1(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _PartNum = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  15 :
                            state = 18;
                            continue outer;
                        case  8 :
                            if (("quantity" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 9;
                                return ;
                            }
                            break;
                        case  11 :
                            if (("USPrice" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 12;
                                return ;
                            }
                            break;
                        case  14 :
                            if (("comment" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 15;
                                return ;
                            }
                            break;
                        case  0 :
                            attIdx = context.getAttribute("", "partNum");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 3;
                                continue outer;
                            }
                            break;
                        case  5 :
                            if (("productName" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 6;
                                return ;
                            }
                            break;
                        case  18 :
                            revertToParentFromLeaveElement(___uri, ___local, ___qname);
                            return ;
                        case  12 :
                            state = 15;
                            continue outer;
                        case  17 :
                            if (("shipDate" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 18;
                                return ;
                            }
                            break;
                    }
                    super.leaveElement(___uri, ___local, ___qname);
                    break;
                }
            }

            public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  15 :
                            state = 18;
                            continue outer;
                        case  0 :
                            if (("partNum" == ___local)&&("" == ___uri)) {
                                state = 1;
                                return ;
                            }
                            break;
                        case  18 :
                            revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                            return ;
                        case  12 :
                            state = 15;
                            continue outer;
                    }
                    super.enterAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  15 :
                            state = 18;
                            continue outer;
                        case  0 :
                            attIdx = context.getAttribute("", "partNum");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 3;
                                continue outer;
                            }
                            break;
                        case  18 :
                            revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                            return ;
                        case  12 :
                            state = 15;
                            continue outer;
                        case  2 :
                            if (("partNum" == ___local)&&("" == ___uri)) {
                                state = 3;
                                return ;
                            }
                            break;
                    }
                    super.leaveAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void handleText(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    try {
                        switch (state) {
                            case  13 :
                                eatText2(value);
                                state = 14;
                                return ;
                            case  15 :
                                state = 18;
                                continue outer;
                            case  16 :
                                eatText3(value);
                                state = 17;
                                return ;
                            case  7 :
                                eatText4(value);
                                state = 8;
                                return ;
                            case  10 :
                                eatText5(value);
                                state = 11;
                                return ;
                            case  0 :
                                attIdx = context.getAttribute("", "partNum");
                                if (attIdx >= 0) {
                                    final java.lang.String v = context.eatAttribute(attIdx);
                                    eatText1(v);
                                    state = 3;
                                    continue outer;
                                }
                                break;
                            case  18 :
                                revertToParentFromText(value);
                                return ;
                            case  12 :
                                state = 15;
                                continue outer;
                            case  4 :
                                eatText6(value);
                                state = 5;
                                return ;
                            case  1 :
                                eatText1(value);
                                state = 2;
                                return ;
                        }
                    } catch (java.lang.RuntimeException e) {
                        handleUnexpectedTextException(value, e);
                    }
                    break;
                }
            }

            private void eatText2(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Comment = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText3(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _ShipDate = javax.xml.bind.DatatypeConverter.parseDate(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText4(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Quantity = javax.xml.bind.DatatypeConverter.parseInteger(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText5(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _USPrice = javax.xml.bind.DatatypeConverter.parseDecimal(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText6(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _ProductName = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

        }

    }

    public class Unmarshaller
        extends org.megatome.frame2.jaxbgen.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.megatome.frame2.jaxbgen.impl.ItemsImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        if (("item" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "partNum");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  0 :
                        if (("item" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "partNum");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  2 :
                        if (("item" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        if (("partNum" == ___local)&&("" == ___uri)) {
                            _Item.add(((org.megatome.frame2.jaxbgen.impl.ItemsImpl.ItemTypeImpl) spawnChildFromEnterAttribute((org.megatome.frame2.jaxbgen.impl.ItemsImpl.ItemTypeImpl.class), 2, ___uri, ___local, ___qname)));
                            return ;
                        }
                        break;
                    case  0 :
                        state = 3;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "partNum");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  0 :
                        state = 3;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                        case  1 :
                            attIdx = context.getAttribute("", "partNum");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  0 :
                            state = 3;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
