//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.04 at 02:32:08 MST 
//


package org.megatome.frame2.jaxbgen.impl;

public class PurchaseOrderTypeImpl
    extends org.megatome.frame2.jaxb.JaxbEventBase
    implements org.megatome.frame2.jaxbgen.PurchaseOrderType, java.io.Serializable, com.sun.xml.bind.JAXBObject, org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallableObject, org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializable, org.megatome.frame2.jaxbgen.impl.runtime.ValidatableObject
{

    private final static long serialVersionUID = 1L;
    protected org.megatome.frame2.jaxbgen.Items _Items;
    protected java.util.Calendar _OrderDate;
    protected java.lang.String _Comment;
    protected org.megatome.frame2.jaxbgen.USAddress _BillTo;
    protected org.megatome.frame2.jaxbgen.USAddress _ShipTo;
    public final static java.lang.Class version = (org.megatome.frame2.jaxbgen.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.megatome.frame2.jaxbgen.PurchaseOrderType.class);
    }

    public org.megatome.frame2.jaxbgen.Items getItems() {
        return _Items;
    }

    public void setItems(org.megatome.frame2.jaxbgen.Items value) {
        _Items = value;
    }

    public java.util.Calendar getOrderDate() {
        return _OrderDate;
    }

    public void setOrderDate(java.util.Calendar value) {
        _OrderDate = value;
    }

    public java.lang.String getComment() {
        return _Comment;
    }

    public void setComment(java.lang.String value) {
        _Comment = value;
    }

    public org.megatome.frame2.jaxbgen.USAddress getBillTo() {
        return _BillTo;
    }

    public void setBillTo(org.megatome.frame2.jaxbgen.USAddress value) {
        _BillTo = value;
    }

    public org.megatome.frame2.jaxbgen.USAddress getShipTo() {
        return _ShipTo;
    }

    public void setShipTo(org.megatome.frame2.jaxbgen.USAddress value) {
        _ShipTo = value;
    }

    public org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context) {
        return new org.megatome.frame2.jaxbgen.impl.PurchaseOrderTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "shipTo");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ShipTo), "ShipTo");
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ShipTo), "ShipTo");
        context.endAttributes();
        context.childAsBody(((com.sun.xml.bind.JAXBObject) _ShipTo), "ShipTo");
        context.endElement();
        context.startElement("", "billTo");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _BillTo), "BillTo");
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _BillTo), "BillTo");
        context.endAttributes();
        context.childAsBody(((com.sun.xml.bind.JAXBObject) _BillTo), "BillTo");
        context.endElement();
        if (_Comment!= null) {
            context.startElement("", "comment");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Comment), "Comment");
            } catch (java.lang.Exception e) {
                org.megatome.frame2.jaxbgen.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        context.startElement("", "items");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Items), "Items");
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Items), "Items");
        context.endAttributes();
        context.childAsBody(((com.sun.xml.bind.JAXBObject) _Items), "Items");
        context.endElement();
    }

    public void serializeAttributes(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_OrderDate!= null) {
            context.startAttribute("", "orderDate");
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDate(((java.util.Calendar) _OrderDate)), "OrderDate");
            } catch (java.lang.Exception e) {
                org.megatome.frame2.jaxbgen.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
    }

    public void serializeURIs(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.megatome.frame2.jaxbgen.PurchaseOrderType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava"
+"/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\n,0\nppsq\u0000~\u0000\u0000\bU\u0085\u00acppsq\u0000~\u0000\u0000\u0005"
+" \u0088_ppsq\u0000~\u0000\u0000\u00041}\u00cbppsr\u0000\'com.sun.msv.grammar.trex.ElementPattern"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000"
+"\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclare"
+"dAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0002\u001f\u00db\tpp\u0000sq\u0000~\u0000\u0000\u0002\u001f\u00da\u00feppsq\u0000~"
+"\u0000\t\u0001G\u00c1\u00fdpp\u0000sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0001"
+"G\u00c1\u00f2ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom."
+"sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0001G\u00c1\u00e7sr\u0000\u0011"
+"java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com.sun.msv.gram"
+"mar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\nxq\u0000~\u0000"
+"\u0003\u0001G\u00c1\u00e4q\u0000~\u0000\u0015psr\u00002com.sun.msv.grammar.Expression$AnyStringExpre"
+"ssion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bsq\u0000~\u0000\u0014\u0001q\u0000~\u0000\u0019sr\u0000 com.sun.msv.gramma"
+"r.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$EpsilonExpress"
+"ion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tq\u0000~\u0000\u001apsr\u0000#com.sun.msv.grammar.Simple"
+"NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fname"
+"spaceURIq\u0000~\u0000!xq\u0000~\u0000\u001ct\u0000%org.megatome.frame2.jaxbgen.USAddresst"
+"\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u000f\u0000\u00d8\u0018\u00fcppsq\u0000"
+"~\u0000\u0016\u0000\u00d8\u0018\u00f1q\u0000~\u0000\u0015psr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dt"
+"t\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLc"
+"om/sun/msv/util/StringPair;xq\u0000~\u0000\u0003\u0000\u0097\u00ed\u00fdppsr\u0000\"com.sun.msv.datat"
+"ype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.Bui"
+"ltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.Concre"
+"teType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000!L\u0000\btypeNameq\u0000~\u0000!L\u0000\nwhiteSpace"
+"t\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http:/"
+"/www.w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.x"
+"sd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.da"
+"tatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.g"
+"rammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr"
+"\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000!L\u0000\f"
+"namespaceURIq\u0000~\u0000!xpq\u0000~\u00002q\u0000~\u00001sq\u0000~\u0000 t\u0000\u0004typet\u0000)http://www.w3.o"
+"rg/2001/XMLSchema-instanceq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u0006shipTot\u0000\u0000sq\u0000~\u0000\t\u0002\u0011\u00a2\u00bdp"
+"p\u0000sq\u0000~\u0000\u0000\u0002\u0011\u00a2\u00b2ppsq\u0000~\u0000\t\u0001G\u00c1\u00fdpp\u0000sq\u0000~\u0000\u000f\u0001G\u00c1\u00f2ppsq\u0000~\u0000\u0011\u0001G\u00c1\u00e7q\u0000~\u0000\u0015psq\u0000~\u0000"
+"\u0016\u0001G\u00c1\u00e4q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 q\u0000~\u0000#q\u0000~\u0000$sq\u0000~\u0000\u000f\u0000\u00c9\u00e0\u00b0ppsq\u0000~\u0000\u0016"
+"\u0000\u00c9\u00e0\u00a5q\u0000~\u0000\u0015pq\u0000~\u0000*sq\u0000~\u0000 q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u0006billToq\u0000~\u0000?sq\u0000~"
+"\u0000\u000f\u0000\u00ef\n\u008fppsq\u0000~\u0000\t\u0000\u00ef\n\u0084q\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0000\u0000\u00ef\nyppsq\u0000~\u0000\'\u00002W\u00c8ppsr\u0000#com.sun"
+".msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000"
+",q\u0000~\u00001t\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProces"
+"sor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00004\u0001q\u0000~\u00007sq\u0000~\u00008q\u0000~\u0000Rq\u0000~\u00001sq\u0000~\u0000\u000f\u0000\u00bc\u00b2"
+"\u00acppsq\u0000~\u0000\u0016\u0000\u00bc\u00b2\u00a1q\u0000~\u0000\u0015pq\u0000~\u0000*sq\u0000~\u0000 q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u0007commen"
+"tq\u0000~\u0000?q\u0000~\u0000\u001fsq\u0000~\u0000\t\u00034\u00fdHpp\u0000sq\u0000~\u0000\u0000\u00034\u00fd=ppsq\u0000~\u0000\t\u0001G\u00c1\u00fdpp\u0000sq\u0000~\u0000\u000f\u0001G\u00c1\u00f2p"
+"psq\u0000~\u0000\u0011\u0001G\u00c1\u00e7q\u0000~\u0000\u0015psq\u0000~\u0000\u0016\u0001G\u00c1\u00e4q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000!org"
+".megatome.frame2.jaxbgen.Itemsq\u0000~\u0000$sq\u0000~\u0000\u000f\u0001\u00ed;;ppsq\u0000~\u0000\u0016\u0001\u00ed;0q\u0000~"
+"\u0000\u0015pq\u0000~\u0000*sq\u0000~\u0000 q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u0005itemsq\u0000~\u0000?sq\u0000~\u0000\u000f\u0001\u00d6\u00aaYpp"
+"sq\u0000~\u0000\u0016\u0001\u00d6\u00aaNq\u0000~\u0000\u0015psq\u0000~\u0000\'\u0001\u00c2\b\u00c0ppsr\u0000!com.sun.msv.datatype.xsd.Dat"
+"eType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000)com.sun.msv.datatype.xsd.DateTimeBaseTyp"
+"e\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u0000,q\u0000~\u00001t\u0000\u0004dateq\u0000~\u00005q\u0000~\u00007sq\u0000~\u00008q\u0000~\u0000nq\u0000~\u00001sq\u0000~"
+"\u0000 t\u0000\torderDateq\u0000~\u0000?q\u0000~\u0000\u001fsr\u0000\"com.sun.msv.grammar.ExpressionPo"
+"ol\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPo"
+"ol$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$Close"
+"dHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006parentq\u0000~\u0000s[\u0000\u0005tablet\u0000"
+"![Lcom/sun/msv/grammar/Expression;xp\u0000\u0000\u0000\u0014\u0000\u0000\u00009pur\u0000![Lcom.sun.m"
+"sv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppq\u0000~\u0000\u0006ppppppppppppp"
+"pppppq\u0000~\u0000Vppppppppq\u0000~\u0000\\pppppppppppppppppppq\u0000~\u0000\u0013q\u0000~\u0000Dq\u0000~\u0000_ppp"
+"pppppq\u0000~\u0000\u0010q\u0000~\u0000Cq\u0000~\u0000^pppq\u0000~\u0000Gppppppppppppppppppppppppppq\u0000~\u0000%p"
+"pppppppppppppppppppppppppppppppppppppppppppppppq\u0000~\u0000cpq\u0000~\u0000Aq\u0000"
+"~\u0000\u0007pppppppq\u0000~\u0000\bq\u0000~\u0000Nppppppppppppppppq\u0000~\u0000\rpq\u0000~\u0000hppq\u0000~\u0000Lppppq\u0000"
+"~\u0000\u0005ppppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.megatome.frame2.jaxbgen.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------");
        }

        protected Unmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.megatome.frame2.jaxbgen.impl.PurchaseOrderTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        if (("shipTo" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 4;
                            return ;
                        }
                        break;
                    case  12 :
                        if (("items" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 13;
                            return ;
                        }
                        break;
                    case  15 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "orderDate");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  6 :
                        if (("billTo" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 7;
                            return ;
                        }
                        break;
                    case  7 :
                        attIdx = context.getAttribute("", "country");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("name" == ___local)&&("" == ___uri)) {
                            _BillTo = ((org.megatome.frame2.jaxbgen.impl.USAddressImpl) spawnChildFromEnterElement((org.megatome.frame2.jaxbgen.impl.USAddressImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  4 :
                        attIdx = context.getAttribute("", "country");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("name" == ___local)&&("" == ___uri)) {
                            _ShipTo = ((org.megatome.frame2.jaxbgen.impl.USAddressImpl) spawnChildFromEnterElement((org.megatome.frame2.jaxbgen.impl.USAddressImpl.class), 5, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  9 :
                        if (("comment" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        state = 12;
                        continue outer;
                    case  13 :
                        if (("item" == ___local)&&("" == ___uri)) {
                            _Items = ((org.megatome.frame2.jaxbgen.impl.ItemsImpl) spawnChildFromEnterElement((org.megatome.frame2.jaxbgen.impl.ItemsImpl.class), 14, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _Items = ((org.megatome.frame2.jaxbgen.impl.ItemsImpl) spawnChildFromEnterElement((org.megatome.frame2.jaxbgen.impl.ItemsImpl.class), 14, ___uri, ___local, ___qname, __atts));
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _OrderDate = javax.xml.bind.DatatypeConverter.parseDate(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  14 :
                        if (("items" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  15 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  11 :
                        if (("comment" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("billTo" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  0 :
                        attIdx = context.getAttribute("", "orderDate");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  7 :
                        attIdx = context.getAttribute("", "country");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  4 :
                        attIdx = context.getAttribute("", "country");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  13 :
                        _Items = ((org.megatome.frame2.jaxbgen.impl.ItemsImpl) spawnChildFromLeaveElement((org.megatome.frame2.jaxbgen.impl.ItemsImpl.class), 14, ___uri, ___local, ___qname));
                        return ;
                    case  5 :
                        if (("shipTo" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  15 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        if (("orderDate" == ___local)&&("" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  7 :
                        if (("country" == ___local)&&("" == ___uri)) {
                            _BillTo = ((org.megatome.frame2.jaxbgen.impl.USAddressImpl) spawnChildFromEnterAttribute((org.megatome.frame2.jaxbgen.impl.USAddressImpl.class), 8, ___uri, ___local, ___qname));
                            return ;
                        }
                        break;
                    case  4 :
                        if (("country" == ___local)&&("" == ___uri)) {
                            _ShipTo = ((org.megatome.frame2.jaxbgen.impl.USAddressImpl) spawnChildFromEnterAttribute((org.megatome.frame2.jaxbgen.impl.USAddressImpl.class), 5, ___uri, ___local, ___qname));
                            return ;
                        }
                        break;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  13 :
                        _Items = ((org.megatome.frame2.jaxbgen.impl.ItemsImpl) spawnChildFromEnterAttribute((org.megatome.frame2.jaxbgen.impl.ItemsImpl.class), 14, ___uri, ___local, ___qname));
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  2 :
                        if (("orderDate" == ___local)&&("" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                    case  15 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "orderDate");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  7 :
                        attIdx = context.getAttribute("", "country");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  4 :
                        attIdx = context.getAttribute("", "country");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  13 :
                        _Items = ((org.megatome.frame2.jaxbgen.impl.ItemsImpl) spawnChildFromLeaveAttribute((org.megatome.frame2.jaxbgen.impl.ItemsImpl.class), 14, ___uri, ___local, ___qname));
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  15 :
                            revertToParentFromText(value);
                            return ;
                        case  1 :
                            eatText1(value);
                            state = 2;
                            return ;
                        case  10 :
                            eatText2(value);
                            state = 11;
                            return ;
                        case  0 :
                            attIdx = context.getAttribute("", "orderDate");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 3;
                                continue outer;
                            }
                            state = 3;
                            continue outer;
                        case  7 :
                            attIdx = context.getAttribute("", "country");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  4 :
                            attIdx = context.getAttribute("", "country");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  9 :
                            state = 12;
                            continue outer;
                        case  13 :
                            _Items = ((org.megatome.frame2.jaxbgen.impl.ItemsImpl) spawnChildFromText((org.megatome.frame2.jaxbgen.impl.ItemsImpl.class), 14, value));
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Comment = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
