//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.04 at 02:32:08 MST 
//


package org.megatome.frame2.jaxbgen.impl;

public class PurchaseOrderImpl
    extends org.megatome.frame2.jaxbgen.impl.PurchaseOrderTypeImpl
    implements org.megatome.frame2.jaxbgen.PurchaseOrder, java.io.Serializable, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallableObject, org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializable, org.megatome.frame2.jaxbgen.impl.runtime.ValidatableObject
{

    private final static long serialVersionUID = 1L;
    public final static java.lang.Class version = (org.megatome.frame2.jaxbgen.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.megatome.frame2.jaxbgen.PurchaseOrder.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "purchaseOrder";
    }

    public org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context) {
        return new org.megatome.frame2.jaxbgen.impl.PurchaseOrderImpl.Unmarshaller(context);
    }

    public void serializeBody(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "purchaseOrder");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(org.megatome.frame2.jaxbgen.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.megatome.frame2.jaxbgen.PurchaseOrder.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilon"
+"Reducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xp\f6Byp"
+"p\u0000sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~"
+"\u0000\u0004\f6Bnppsq\u0000~\u0000\u0007\n,0\nppsq\u0000~\u0000\u0007\bU\u0085\u00acppsq\u0000~\u0000\u0007\u0005 \u0088_ppsq\u0000~\u0000\u0007\u00041}\u00cbppsq\u0000~"
+"\u0000\u0000\u0002\u001f\u00db\tpp\u0000sq\u0000~\u0000\u0007\u0002\u001f\u00da\u00feppsq\u0000~\u0000\u0000\u0001G\u00c1\u00fdpp\u0000sr\u0000\u001dcom.sun.msv.grammar.Ch"
+"oiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\b\u0001G\u00c1\u00f2ppsr\u0000 com.sun.msv.grammar.OneOrM"
+"oreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001"
+"L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004\u0001G\u00c1\u00e7sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valu"
+"exp\u0000psr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000"
+"~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004\u0001G\u00c1\u00e4q\u0000~\u0000\u0017psr\u00002com.sun.msv.grammar."
+"Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\bsq\u0000~\u0000\u0016\u0001q\u0000"
+"~\u0000\u001bsr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar."
+"Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\tq\u0000~\u0000\u001cpsr\u0000#c"
+"om.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012"
+"Ljava/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000#xq\u0000~\u0000\u001et\u0000%org.megatome."
+"frame2.jaxbgen.USAddresst\u0000+http://java.sun.com/jaxb/xjc/dumm"
+"y-elementssq\u0000~\u0000\u0011\u0000\u00d8\u0018\u00fcppsq\u0000~\u0000\u0018\u0000\u00d8\u0018\u00f1q\u0000~\u0000\u0017psr\u0000\u001bcom.sun.msv.gramma"
+"r.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L"
+"\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0004\u0000\u0097"
+"\u00ed\u00fdppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com"
+".sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.su"
+"n.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.da"
+"tatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000#L\u0000\bt"
+"ypeNameq\u0000~\u0000#L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteS"
+"paceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0005QNames"
+"r\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$NullSetExpression"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f"
+"\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000#L\u0000\fnamespaceURIq\u0000~\u0000#xpq\u0000~\u00004q\u0000~\u00003sq\u0000~\u0000\""
+"t\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instanceq\u0000~\u0000!sq\u0000~"
+"\u0000\"t\u0000\u0006shipTot\u0000\u0000sq\u0000~\u0000\u0000\u0002\u0011\u00a2\u00bdpp\u0000sq\u0000~\u0000\u0007\u0002\u0011\u00a2\u00b2ppsq\u0000~\u0000\u0000\u0001G\u00c1\u00fdpp\u0000sq\u0000~\u0000\u0011\u0001G"
+"\u00c1\u00f2ppsq\u0000~\u0000\u0013\u0001G\u00c1\u00e7q\u0000~\u0000\u0017psq\u0000~\u0000\u0018\u0001G\u00c1\u00e4q\u0000~\u0000\u0017pq\u0000~\u0000\u001bq\u0000~\u0000\u001fq\u0000~\u0000!sq\u0000~\u0000\"q\u0000~"
+"\u0000%q\u0000~\u0000&sq\u0000~\u0000\u0011\u0000\u00c9\u00e0\u00b0ppsq\u0000~\u0000\u0018\u0000\u00c9\u00e0\u00a5q\u0000~\u0000\u0017pq\u0000~\u0000,sq\u0000~\u0000\"q\u0000~\u0000=q\u0000~\u0000>q\u0000~\u0000"
+"!sq\u0000~\u0000\"t\u0000\u0006billToq\u0000~\u0000Asq\u0000~\u0000\u0011\u0000\u00ef\n\u008fppsq\u0000~\u0000\u0000\u0000\u00ef\n\u0084q\u0000~\u0000\u0017p\u0000sq\u0000~\u0000\u0007\u0000\u00ef\ny"
+"ppsq\u0000~\u0000)\u00002W\u00c8ppsr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000.q\u0000~\u00003t\u0000\u0006stringsr\u00005com.sun.msv.data"
+"type.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00006\u0001q\u0000~\u00009"
+"sq\u0000~\u0000:q\u0000~\u0000Tq\u0000~\u00003sq\u0000~\u0000\u0011\u0000\u00bc\u00b2\u00acppsq\u0000~\u0000\u0018\u0000\u00bc\u00b2\u00a1q\u0000~\u0000\u0017pq\u0000~\u0000,sq\u0000~\u0000\"q\u0000~\u0000="
+"q\u0000~\u0000>q\u0000~\u0000!sq\u0000~\u0000\"t\u0000\u0007commentq\u0000~\u0000Aq\u0000~\u0000!sq\u0000~\u0000\u0000\u00034\u00fdHpp\u0000sq\u0000~\u0000\u0007\u00034\u00fd=p"
+"psq\u0000~\u0000\u0000\u0001G\u00c1\u00fdpp\u0000sq\u0000~\u0000\u0011\u0001G\u00c1\u00f2ppsq\u0000~\u0000\u0013\u0001G\u00c1\u00e7q\u0000~\u0000\u0017psq\u0000~\u0000\u0018\u0001G\u00c1\u00e4q\u0000~\u0000\u0017pq\u0000"
+"~\u0000\u001bq\u0000~\u0000\u001fq\u0000~\u0000!sq\u0000~\u0000\"t\u0000!org.megatome.frame2.jaxbgen.Itemsq\u0000~\u0000&"
+"sq\u0000~\u0000\u0011\u0001\u00ed;;ppsq\u0000~\u0000\u0018\u0001\u00ed;0q\u0000~\u0000\u0017pq\u0000~\u0000,sq\u0000~\u0000\"q\u0000~\u0000=q\u0000~\u0000>q\u0000~\u0000!sq\u0000~\u0000\""
+"t\u0000\u0005itemsq\u0000~\u0000Asq\u0000~\u0000\u0011\u0001\u00d6\u00aaYppsq\u0000~\u0000\u0018\u0001\u00d6\u00aaNq\u0000~\u0000\u0017psq\u0000~\u0000)\u0001\u00c2\b\u00c0ppsr\u0000!com"
+".sun.msv.datatype.xsd.DateType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000)com.sun.msv.dat"
+"atype.xsd.DateTimeBaseType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u0000.q\u0000~\u00003t\u0000\u0004dateq\u0000~\u00007"
+"q\u0000~\u00009sq\u0000~\u0000:q\u0000~\u0000pq\u0000~\u00003sq\u0000~\u0000\"t\u0000\torderDateq\u0000~\u0000Aq\u0000~\u0000!sq\u0000~\u0000\u0011\u0002\n\u0012_p"
+"psq\u0000~\u0000\u0018\u0002\n\u0012Tq\u0000~\u0000\u0017pq\u0000~\u0000,sq\u0000~\u0000\"q\u0000~\u0000=q\u0000~\u0000>q\u0000~\u0000!sq\u0000~\u0000\"t\u0000\rpurchase"
+"Orderq\u0000~\u0000Asr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L"
+"\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;"
+"xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002"
+"\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006parentq\u0000~\u0000z[\u0000\u0005tablet\u0000![Lcom/sun/msv"
+"/grammar/Expression;xp\u0000\u0000\u0000\u0016\u0000\u0000\u00009pur\u0000![Lcom.sun.msv.grammar.Exp"
+"ression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppq\u0000~\u0000\u000bppppppppppppppppppq\u0000~\u0000Xpppp"
+"ppppq\u0000~\u0000^pppppppppppppppppppq\u0000~\u0000\u0015q\u0000~\u0000Fq\u0000~\u0000appppppppq\u0000~\u0000\u0012q\u0000~\u0000"
+"Eq\u0000~\u0000`pppq\u0000~\u0000Ippppppppppppppppppppq\u0000~\u0000\tppq\u0000~\u0000tppq\u0000~\u0000\'ppppppp"
+"pppppppppppppppppppppppppppppppppppppppppq\u0000~\u0000epq\u0000~\u0000Cq\u0000~\u0000\fppp"
+"ppppq\u0000~\u0000\rq\u0000~\u0000Pppppppppppppppppq\u0000~\u0000\u000fpq\u0000~\u0000jppq\u0000~\u0000Nppppq\u0000~\u0000\nppp"
+"pppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.megatome.frame2.jaxbgen.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(org.megatome.frame2.jaxbgen.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.megatome.frame2.jaxbgen.impl.PurchaseOrderImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        if (("purchaseOrder" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "orderDate");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("shipTo" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((org.megatome.frame2.jaxbgen.impl.PurchaseOrderTypeImpl)org.megatome.frame2.jaxbgen.impl.PurchaseOrderImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  2 :
                        if (("purchaseOrder" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "orderDate");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        if (("orderDate" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((org.megatome.frame2.jaxbgen.impl.PurchaseOrderTypeImpl)org.megatome.frame2.jaxbgen.impl.PurchaseOrderImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "orderDate");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                        case  1 :
                            attIdx = context.getAttribute("", "orderDate");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
