//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.05.09 at 09:13:58 MDT 
//


package org.megatome.app.jaxbgen;


/**
 * Java content class for comment element declaration.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * </pre>
 * 
 */
public interface Comment
    extends javax.xml.bind.Element
{


    java.lang.String getValue();

    void setValue(java.lang.String value);

}
