//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.12 at 08:53:07 MST 
//


package org.megatome.app.jaxbgen;


/**
 * Java content class for user element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/xjc/user.xsd line 21)
 * <p>
 * <pre>
 * &lt;element name="user">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element ref="{}comment" minOccurs="0"/>
 *           &lt;element name="email" type="{}EmailType"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface User
    extends javax.xml.bind.Element, org.megatome.app.jaxbgen.UserType
{


}
