//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.04 at 02:32:08 MST 
//


package org.megatome.frame2.jaxbgen;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.megatome.frame2.jaxbgen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends org.megatome.frame2.jaxbgen.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap();
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static org.megatome.frame2.jaxbgen.impl.runtime.GrammarInfo grammarInfo = new org.megatome.frame2.jaxbgen.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (org.megatome.frame2.jaxbgen.ObjectFactory.class));
    public final static java.lang.Class version = (org.megatome.frame2.jaxbgen.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((org.megatome.frame2.jaxbgen.Items.ItemType.class), "org.megatome.frame2.jaxbgen.impl.ItemsImpl.ItemTypeImpl");
        defaultImplementations.put((org.megatome.frame2.jaxbgen.USAddress.class), "org.megatome.frame2.jaxbgen.impl.USAddressImpl");
        defaultImplementations.put((org.megatome.frame2.jaxbgen.PurchaseOrder.class), "org.megatome.frame2.jaxbgen.impl.PurchaseOrderImpl");
        defaultImplementations.put((org.megatome.frame2.jaxbgen.PurchaseOrderType.class), "org.megatome.frame2.jaxbgen.impl.PurchaseOrderTypeImpl");
        defaultImplementations.put((org.megatome.frame2.jaxbgen.Comment.class), "org.megatome.frame2.jaxbgen.impl.CommentImpl");
        defaultImplementations.put((org.megatome.frame2.jaxbgen.Items.class), "org.megatome.frame2.jaxbgen.impl.ItemsImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "purchaseOrder"), (org.megatome.frame2.jaxbgen.PurchaseOrder.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "comment"), (org.megatome.frame2.jaxbgen.Comment.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.megatome.frame2.jaxbgen
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of ItemsItemType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.megatome.frame2.jaxbgen.Items.ItemType createItemsItemType()
        throws javax.xml.bind.JAXBException
    {
        return new org.megatome.frame2.jaxbgen.impl.ItemsImpl.ItemTypeImpl();
    }

    /**
     * Create an instance of USAddress
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.megatome.frame2.jaxbgen.USAddress createUSAddress()
        throws javax.xml.bind.JAXBException
    {
        return new org.megatome.frame2.jaxbgen.impl.USAddressImpl();
    }

    /**
     * Create an instance of PurchaseOrder
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.megatome.frame2.jaxbgen.PurchaseOrder createPurchaseOrder()
        throws javax.xml.bind.JAXBException
    {
        return new org.megatome.frame2.jaxbgen.impl.PurchaseOrderImpl();
    }

    /**
     * Create an instance of PurchaseOrderType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.megatome.frame2.jaxbgen.PurchaseOrderType createPurchaseOrderType()
        throws javax.xml.bind.JAXBException
    {
        return new org.megatome.frame2.jaxbgen.impl.PurchaseOrderTypeImpl();
    }

    /**
     * Create an instance of Comment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.megatome.frame2.jaxbgen.Comment createComment()
        throws javax.xml.bind.JAXBException
    {
        return new org.megatome.frame2.jaxbgen.impl.CommentImpl();
    }

    /**
     * Create an instance of Comment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.megatome.frame2.jaxbgen.Comment createComment(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.megatome.frame2.jaxbgen.impl.CommentImpl(value);
    }

    /**
     * Create an instance of Items
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.megatome.frame2.jaxbgen.Items createItems()
        throws javax.xml.bind.JAXBException
    {
        return new org.megatome.frame2.jaxbgen.impl.ItemsImpl();
    }

}
