//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.04 at 02:32:08 MST 
//


package org.megatome.frame2.jaxbgen;


/**
 * Java content class for purchaseOrder element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/eclipse/frame2/Frame2/framework/test/xml/po.xsd line 19)
 * <p>
 * <pre>
 * &lt;element name="purchaseOrder" type="{}PurchaseOrderType"/>
 * </pre>
 * 
 */
public interface PurchaseOrder
    extends javax.xml.bind.Element, org.megatome.frame2.jaxbgen.PurchaseOrderType
{


}
