//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.04 at 02:32:08 MST 
//


package org.megatome.frame2.jaxbgen;


/**
 * Java content class for PurchaseOrderType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/eclipse/frame2/Frame2/framework/test/xml/po.xsd line 23)
 * <p>
 * <pre>
 * &lt;complexType name="PurchaseOrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shipTo" type="{}USAddress"/>
 *         &lt;element name="billTo" type="{}USAddress"/>
 *         &lt;element ref="{}comment" minOccurs="0"/>
 *         &lt;element name="items" type="{}Items"/>
 *       &lt;/sequence>
 *       &lt;attribute name="orderDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface PurchaseOrderType {


    /**
     * 
     * @return
     *     possible object is
     *     {@link org.megatome.frame2.jaxbgen.Items}
     */
    org.megatome.frame2.jaxbgen.Items getItems();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link org.megatome.frame2.jaxbgen.Items}
     */
    void setItems(org.megatome.frame2.jaxbgen.Items value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getOrderDate();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setOrderDate(java.util.Calendar value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getComment();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setComment(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link org.megatome.frame2.jaxbgen.USAddress}
     */
    org.megatome.frame2.jaxbgen.USAddress getBillTo();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link org.megatome.frame2.jaxbgen.USAddress}
     */
    void setBillTo(org.megatome.frame2.jaxbgen.USAddress value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link org.megatome.frame2.jaxbgen.USAddress}
     */
    org.megatome.frame2.jaxbgen.USAddress getShipTo();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link org.megatome.frame2.jaxbgen.USAddress}
     */
    void setShipTo(org.megatome.frame2.jaxbgen.USAddress value);

}
